### ISSUE TITLE
Required field validator is not working when using skyux-autonumeric with input field

### ISSUE THREAD

**Issue by bb-roopamgupta** [blackbaud/skyux-autonumeric#12]
Reactive form's Required validator  is not working when using skyux-autonumeric with input field. Severity isn't high as we are still developing other components but there isn't any workaround available.

**Comment by Blackbaud-AlexKingman** [comment]
Hey @bb-roopamgupta thanks for submitting this issue! We'll get to work on this very soon, but in the meantime, could you please add some more detail to the ticket description about what you're seeing vs what you're expecting? This format works well ->

#Expected behavior
...

#Actual behavior
...

#Steps to reproduce
...

**Comment by bb-roopamgupta** [comment]
Hi @Blackbaud-AlexKingman , Here is the more detail-

Expected behavior
	Losing focus from text box with sky-autonumeric shouldn't be marked as valid until numeric value is typed. Also, basic required field validation should work.

Actual behavior
	Losing focus from text box with sky-autonumeric is marked as valid without even typing anything. Also, basic required field validation isn't working.

Steps to reproduce
	1. Create a sky-autonumeric text box using reactive form.
	2. Apply required filed validator.
	3. Now focus in and out over the text box and verify the field validity.
